testing-cabal/fixtures

NEWS, README, fixtures/__init__.py, fixtures/_fixtures/environ.py, fixtures/_fixtures/logger.py, fixtures/_fixtures/mockpatch.py, fixtures/_fixtures/monkeypatch.py, fixtures/_fixtures/packagepath.py, fixtures/_fixtures/popen.py, fixtures/_fixtures/pythonpackage.py, fixtures/_fixtures/pythonpath.py, fixtures/_fixtures/streams.py, fixtures/_fixtures/tempdir.py, fixtures/_fixtures/temphomedir.py, fixtures/_fixtures/timeout.py, fixtures/_fixtures/warnings.py, fixtures/fixture.py, fixtures/tests/test_fixture.py
Instead override _setup. (Robert Collins, #1456361, #1456353)
=> Fixture.setUp should no longer be overridden.

setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/29)
=> Avoid old versions of pbr - we require modern releases.

NEWS, README, fixtures/_fixtures/monkeypatch.py, fixtures/tests/_fixtures/test_monkeypatch.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/30)
=> Overhaul monkeypatching again

HACKING, NEWS, README, fixtures/callmany.py, fixtures/fixture.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/41)
=> Correct spelling mistakes.

.github/workflows/ci.yaml, NEWS, setup.cfg, tox.ini
Tests will fail until #55 is merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/56)
=> Add support for Python 3.10

NEWS, fixtures/_fixtures/popen.py, fixtures/tests/_fixtures/test_popen.py
This takes over and completes #54.
Fixes #53.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/58)
=> Support all Popen arguments up to Python 3.10

fixtures/tests/_fixtures/test_popen.py
Make sure we maintain compatibility as subprocess.Popen changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/59)
=> Validate function signature of FakePopen

fixtures/_fixtures/popen.py, fixtures/tests/_fixtures/test_popen.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/68)
=> Support Popen's process_group argument from Python 3.11

.github/workflows/ci.yaml, tox.ini
Add py311 to tox.ini, and py311 + all 3 pypy3 versions to GitHub Actions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/69)
=> Add Python 3.11 & PyPy3 to test matrix

NEWS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/71)
=> Release 4.0.1

.github/workflows/ci.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/78)
=> github: Update actions, switch to 3.11 by default

README.rst, setup.cfg
Improve the formatting of the README and add documentation for undocumented
fixtures.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/76)
=> README tweaks

README.rst
I forgot I was editing reStructuredText, not markdown /o\
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/79)
=> README: Use actual admonitions

NEWS
There's enough here to warrant a new minor version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/80)
=> Release 4.1.0

.github/workflows/ci.yaml, fixtures/__init__.py, fixtures/fixture.py, fixtures/tests/_fixtures/test_logger.py, fixtures/tests/_fixtures/test_monkeypatch.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/82)
=> Fix ruff issues and run ruff in CI

.github/workflows/ci.yaml, Makefile, NEWS, README.rst, fixtures/_fixtures/popen.py, setup.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/87)
=> Drop python 3.7 support

README.rst, fixtures/_fixtures/mockpatch.py, fixtures/tests/_fixtures/test_mockpatch.py, setup.cfg
Fixes: #88
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/89)
=> Drop support for external mock package

.github/workflows/ci.yaml, fixtures/tests/_fixtures/test_popen.py, setup.cfg, tox.ini
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/90)
=> Add support for Python 3.13

NEWS
I forgot we had Trusted Publishing set up here.  Probably best to replace my manual upload.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/92)
=> Release 4.2.1

NEWS
Sorry for making a mess here!  4.2.1 was a bit broken because:
```console
$ git push origin master 4.2.1
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 12 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 353 bytes | 353.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote:
remote: - Changes must be made through a pull request.
remote:
remote: - 3 of 3 required status checks are expected.
To git+ssh://github.com/testing-cabal/fixtures
* [new tag]         4.2.1 -> 4.2.1
! [remote rejected] master -> master (protected branch hook declined) …
```
=> Release 4.2.2

ChangeLog, pyproject.toml
Fixes #103
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/104)
=> Add missing Apache license file to sdist
