testing-cabal/fixtures

fixtures/_fixtures/logger.py, fixtures/tests/_fixtures/test_logger.py
When working on OpenStack in tree functional test things like the
context information is extremely useful to have access to. This relies
on using custom log formatter, which currently can't be done in
fixtures.
The creates an additional optional parameter for FakeLogger to specify
this.
=> allow the specification of a custom log formatter

NEWS, fixtures/__init__.py, fixtures/_fixtures/__init__.py, fixtures/_fixtures/warnings.py, fixtures/tests/_fixtures/test_warnings.py
Capturing the warnings module output (which is typically used
for deprecating code or functions or modules) is quite useful and
is a frequent operation that can be required to perform. So provide
a fixture that is similar (but not the same) as the warnings
``catch_warnings`` context manager that can be used to gather all
warnings emitted and allows people to later analyze them to ensure
they are as they expect.
=> Add a warnings module capture fixure

NEWS, fixtures/_fixtures/logger.py, fixtures/tests/_fixtures/test_logger.py
When using the FakeLogger, have mis-formatted logging messages raise an
exception.
Normally when using the logging module, mis-formatted logging messages
will not raise an exception. Instead the exception will be printed but
not raised.
Change this behavior so that mis-formatted log messages can be caught
during unit-testing.
Closes-Bug: #1503049
Change-Id: I8d3e94d131289300ae020eb1d63306489e986335
=> FakeLogger: Mis-formatted log messages will raise Exception

NEWS, README, fixtures/callmany.py, fixtures/fixture.py, fixtures/tests/test_callmany.py, fixtures/tests/test_fixture.py
Mostly just "cach" -> "catch". Also fixes some whitespace & unused imports while I was there.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/17)
=> Spelling and lint fixes

README
Python 3 tests were failing on the improper usage of print in the README
examples. Print must be used as a method in Python 3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/24)
=> Fix print in README

fixtures/_fixtures/monkeypatch.py, fixtures/tests/_fixtures/test_monkeypatch.py
In Python setattr(Class, name, func) automatically converts a function
into an instancemethod. To keep type(Class.func) as function,
staticmethod(func) must be applied explicitly. This was previously fixed
for Python 2 but the issue exists for 3 as well.
The test for this case was updated to correctly check it. The method
does not become bound until the class it is defined on is instantiated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/23)
=> Python 3 MonkeyPatch staticmethod

.gitignore
.tox is created when running tox for the tests. Ignore it so
it's not accidentally checked in.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/28)
=> Ignore .tox

.travis.yml, tox.ini
Add 3.6 to the list of Python versions that Travis/tox will exercise. Also, switch the pypy3 target to version 3.3 (since pkg_resources is not supported anymore on 3.2).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/36)
=> Add python 3.6 support

.travis.yml, README, fixtures/_fixtures/monkeypatch.py, fixtures/tests/__init__.py, fixtures/tests/_fixtures/test_mockpatch.py, fixtures/tests/_fixtures/test_popen.py, fixtures/tests/test_fixture.py, setup.cfg, tox.ini
The [CI fails with latest master for Python 2.6 builds](https://travis-ci.org/hugovk/fixtures/builds/287401621) which also causes PRs to fail (eg. https://github.com/testing-cabal/fixtures/pull/39).
The easiest way to fix it is to just drop support for Python 2.6. I see testtools already dropped it in
https://github.com/testing-cabal/testtools/pull/198.
* Unsupported since [2013-10-29](https://en.wikipedia.org/wiki/CPython#Version_history)
* https://snarky.ca/stop-using-python-2-6/
* http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html
* http://www.python3statement.org
* Current pip 9 deprecates Python 2.6 support, pip 10 won't support it (https://github.com/pypa/pip/issues/3955)
* Not much PyPI traffic (June 2016) https://github.com/pypa/pip/issues/3796
(Python …
=> Drop support for EOL Python 2.6 and 3.3

.travis.yml, NEWS, README, fixtures/__init__.py, fixtures/_fixtures/logger.py, fixtures/_fixtures/mockpatch.py, fixtures/_fixtures/monkeypatch.py, fixtures/_fixtures/streams.py, fixtures/callmany.py, fixtures/fixture.py, fixtures/tests/_fixtures/test_logger.py, fixtures/tests/_fixtures/test_monkeypatch.py, fixtures/tests/_fixtures/test_popen.py, fixtures/tests/_fixtures/test_pythonpackage.py, fixtures/tests/_fixtures/test_streams.py, requirements.txt, setup.cfg, tox.ini
This requires a rather tricky test fix due to changes in behavior of
the 'classmethod' decorator in Python 3.9. We also take the opportunity
to remove some unnecessary libraries ('extras' and 'six') and generally
tidy things up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/46)
=> Drop Python < 3.6 support, add 3.7 - 3.9 support

fixtures/_fixtures/logger.py, fixtures/tests/_fixtures/test_logger.py
A long test case might emit extensive logs that subunit does not
really handle well [1]. So it is useful to reset the logs stored
in the fixture at certain points in the test execution[2].
To be able to do that this patch adds reset_output() call to the
FakeLogger.
[1] https://bugs.launchpad.net/nova/+bug/1813147
[2] https://review.opendev.org/#/c/656844
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/42)
=> Add possibility to reset the FakeLogger

fixtures/_fixtures/mockpatch.py
Access mock.DEFAULT lazily rather than at import time so "mock" can be overriden with something else.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/52)
=> Access mock.DEFAULT lazily rather than at import time so "mock" can be overriden with something else

.github/workflows/ci.yaml, fixtures/_fixtures/mockpatch.py
The change in #52 broke
`TestMockMultiple.test_mock_patch_without_replacement`, since
`MockPatchMultiple.DEFAULT` no longer worked as a class property.  Fix
this using a metaclass.
For compatibility, I arranged for it to also work as an instance
property; I suspect this isn't much needed since
`MockPatchMultiple.DEFAULT` is normally used as an argument to the
`MockPatchMultiple` constructor so you wouldn't normally have an
instance in hand, but it's easy enough to provide strict compatibility
here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/55)
=> Fix MockPatchMultiple.DEFAULT

NEWS, README.rst, fixtures/_fixtures/streams.py, fixtures/callmany.py, fixtures/fixture.py, setup.cfg
Stop using `testtools.helpers.try_import`, as it's only barely more complex to just write out the `try`/`except` directly.
After that, all that remains to make `testtools` optional and break the cyclic requirement is to deal with its use by streams fixtures.  These intrinsically rely on `testtools`, but are also very much optional, so move the requirement to a new `fixtures[streams]` extra.
Fixes #38.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/62)
=> Move testtools requirement to a "streams" extra

NEWS
Given the use of `python_requires`, it probably isn't strictly necessary to bump the major version for dropping Python version support, but it seems prudent to do so in light of moving the `testtools` requirement to an extra.  (In practice I suspect anyone who needs this fixture was already explicitly requiring `testtools` anyway, but you never know.)
If people are OK with this, then I'll tag it and push to PyPI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/63)
=> Release 4.0.0

fixtures/tests/_fixtures/test_monkeypatch.py
Commit fe83067 has changed TestMonkeyPatch to account for changes
in classmethod handling in CPython 3.9.  Unfortunately, this broke
the tests on PyPy3.9.  Revert to the old expectations when using PyPy.
Fixes #64
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/65)
=> Revert to the previous classmethod expectations for PyPy3.9

fixtures/tests/_fixtures/test_monkeypatch.py
It seems that the classmethod behavior in Python 3.11.0b1 is back
to the one found in Python 3.8.  Adjust the test expectations again.
This time around, we expect the "old-new" behavior in CPython 3.9
and 3.10 only.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/67)
=> Update classmethod expectations (again) for Python 3.11

.github/workflows/ci.yaml, NEWS, README.rst, setup.cfg, tox.ini
It's EOL
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/73)
=> Drop support for Python 3.6

pyproject.toml
Don't explicitly build-require wheel
See https://github.com/pypa/setuptools/commit/f7d30a9529378cf69054b5176249e5457aaf640a
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/74)
=> Don't explicitly build-require wheel

fixtures/testcase.py, fixtures/tests/_fixtures/__init__.py, fixtures/tests/_fixtures/test_warnings.py, tox.ini
In #50, I noticed that we weren't running some recently added tests since they hadn't been added to the hardcoded list of test modules found in `fixtures/tests/_fixtures/__init__.py`. Prevent this happening again by searching the test directory for matching modules instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/75)
=> Replace hardcoded list of tests

NEWS, fixtures/__init__.py, fixtures/_fixtures/__init__.py, fixtures/_fixtures/warnings.py, fixtures/testcase.py, fixtures/tests/_fixtures/__init__.py, fixtures/tests/_fixtures/test_warnings.py, tox.ini
This has enough users around OpenStack to justify adding it to 'fixtures' proper. It's intentionally dumb, since the main purpose of this is to avoid people calling `resetwarnings` in their variant of the fixture, as that clears *all* filters including those we don't control.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/50)
=> Add WarningsFilter fixture

README.rst
This patch enables syntax highlighting on github and PyPI for code examples.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/81)
=> Use code-block directive for python code

.github/workflows/ci.yaml, setup.cfg
Add Python 3.12 to classifiers and test matrix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/85)
=> Enable Python 3.12 support

tox.ini
This was missed when adding Python 3.12 support via #85
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/86)
=> Test Python 3.12 also via tox

NEWS
One NEWS entry had been mistakenly placed under 4.1.0.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/91)
=> Release 4.2.0

.github/workflows/ci.yaml, fixtures/__init__.py, fixtures/_fixtures/environ.py, fixtures/_fixtures/logger.py, fixtures/_fixtures/mockpatch.py, fixtures/_fixtures/monkeypatch.py, fixtures/_fixtures/packagepath.py, fixtures/_fixtures/popen.py, fixtures/_fixtures/pythonpackage.py, fixtures/_fixtures/pythonpath.py, fixtures/_fixtures/streams.py, fixtures/_fixtures/tempdir.py, fixtures/_fixtures/temphomedir.py, fixtures/_fixtures/timeout.py, fixtures/_fixtures/warnings.py, fixtures/callmany.py, fixtures/fixture.py, fixtures/testcase.py, fixtures/tests/__init__.py, pyproject.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/testing-cabal/fixtures/107)
=> Add typing hints
